<a href="https://colab.research.google.com/github/utkarsh6174/machine-learning-projects/blob/main/Diabetes_Prediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

Data COllection and Analysis

In [ ]:
#loading the dataset into a pandas dataframe

diabetes_dataset = pd.read_csv('/content/diabetes.csv')
diabetes_dataset.shape

(768, 9)

In [ ]:
#printing the first 5 rows of the dataset
diabetes_dataset.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
#getting the statistical measures of the data
diabetes_dataset.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [ ]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
diabetes_dataset.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [ ]:
# separating the data and labels
X = diabetes_dataset.drop(columns = 'Outcome' , axis = 1)
Y = diabetes_dataset['Outcome']

Data Standardization

In [ ]:
scaler = StandardScaler()
scaler.fit(X)
standardized_data = scaler.transform(X)

In [ ]:
X  = standardized_data
Y = diabetes_dataset['Outcome']
print(X)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

Train Test splitting

In [ ]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size = 0.2 , stratify = Y,random_state = 2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)

Training the Model

In [ ]:
classifier = svm.SVC(kernel ='linear')

In [ ]:
#training the svm classifier
classifier.fit(X_train , Y_train)

SVC(kernel='linear')

Evaluate the model

Accuracy score

In [ ]:
#accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [ ]:
print("Training data accuracy score: ",training_data_accuracy)

Training data accuracy score:  0.7866449511400652

In [ ]:
X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [ ]:
print("Testing data accuracy score: " , testing_data_accuracy)

Testing data accuracy score:  0.7727272727272727

TESTING DATA ACCURACY : 72.272%


TRAINING DATA ACCURACY : 78.664%

Making a Predictive System

In [ ]:
input_data  = (4,110,92,0,0,37.6,0.191,30)

#change the input_data to numpy array

input_data_as_numpy_array = np.asarray(input_data)

#reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

#standardized the input data

std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print("The person is not diabetic")
else:
  print("The person is diabetic")

[[ 4.00000000e+00  1.10000000e+02  9.20000000e+01 -1.00613962e-16
   3.00685403e-17  3.76000000e+01  1.91000000e-01  3.00000000e+01]]
[1]
The person is diabetic